# Cấu hình gửi email — điền thông tin tài khoản Gmail vào đây
# Cách lấy App Password: https://support.google.com/accounts/answer/185833
email.from=nthaiduong.vn@gmail.com
email.password=vwxn viia tynh tbdt
email.smtp.host=smtp.gmail.com
email.smtp.port=587
